# frozen_string_literal: true
source "https://rubygems.org"
gem 'pry'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'sinatra'
gem 'sqlite3'
gem 'rack'
gem 'activerecord', '4.2.0', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
